### ISSUE TITLE
Tester gesucht

### ISSUE THREAD

**Issue by Schnup89** [Schnup89/LIVY_RING_G2-Tasmota#1]
Auf diesem Wege suche ich Tester für meine Implementierung des LiPo-Stromwächter-Modul "LC708203f"

Bei meinen ersten Versuchen bin ich "abgerutscht" ;) und es gab auf dem Modul einen kleinen Funkenregen, deshalb bin ich mir aktuell nicht sicher ob die Werte bei mir richtig ausgelesen werden können oder nicht.
Falls jemand meine Tasmota Version auf den Ring geflashed hat und Lust/Zeit mitbringt etwas zu testen, bitte bei mir melden.

Thx

**Comment by greynoO** [comment]
Das hat jetzt nicht direkt mit dem Ring zu tun, oder?

**Comment by greynoO** [comment]
Ich habe nicht wirklich viel Ahnung, habe nur mal einen Sonoff geflasht und somit zumindest die Hardware dafür da. Wenn du mir genau sagst, was ich tun soll, könnte ich das ggf. morgen mal versuchen (falls sich sonst niemand meldet).

**Comment by Schnup89** [comment]
Habe einen neuen bestellt, sollte bis zum Wochenende da sein.
Bis dahin Versuche ich mich an den restlichen Sensoren.
Aktuell bin ich am pir Sensor, das schaut eigentlich gut aus.
Sorgen macht mir aktuell nur der Gas / Air Qualität Sensor.

**Comment by blautob** [comment]
Danke für deinen Einsatz!
Kann man irgendwie unterstützen?
Was sind die Probleme beim Gas/ Air Sensor?

**Comment by Schnup89** [comment]
Hab mir gerade nochmal das Datenblatt des GAS Sensors angesehen und festgestellt dass es Programm-Technisch gar nicht so kompliziert ist. https://www.sciosense.com/wp-content/uploads/documents/SC-001255-DS-2-CCS801B-Datasheet-Revision-2.pdf
Mir fehlt aber noch die Zuordnung für den Sensor+ Pin, den habe ich noch nicht herausgefunden.

In der Mittagspause stelle ich die aktuellen Entwicklung ein, dann könntest du dir das mal flashen und ausprobieren.
Du kannst vorher ein Backup durchführen (ohne Gewähr dass es wieder eingespielt werden kann:) ) mit:
python esptool.py -b 115200 --port COM3 read_flash 0x00000 0x400000 flash_4M.bin

**Comment by Schnup89** [comment]
Habe eben die livyringg2tasmo.bin aktualisiert.

Bitte nach der Anleitung flashen, dann sollte wie gehabt Tasmota ein eigenes WLAN aufspannen mit dem ihr das Gerät in euer WLAN verbinden könnt. (Das dauert bis 1 Minute, keine Hektik) 

Wenn ihr die Oberfläche seht, einmal auf "Einstellungen" -> "Vorlage konfigurieren" und oben livyring auswählen.
Damit sollte die Modulkonfiguration für die GPIO's passen. (Unten "Speichern" klicken)

Nach einem Reboot werden euch Werte angezeigt:
Analog1: Gas Sensor PIN
An/Aus1: LED ROT
An/Aus2: LED BLAU
An/Aus3: LED GRÜN
An/Aus4: Piezo ?

Zeigt mal her eure Werte ;)

**Comment by greynoO** [comment]
Flashmodus habe ich noch hinbekommen, Verbindung zum ESP durch bloßes ranhalten noch nicht.

**Comment by Schnup89** [comment]
super, bei mir hat es nur mit dem python script geklappt, machst du es auch damit oder mit einem windows tool?

**Comment by greynoO** [comment]
Ich versuche es über WSL, kriege aber nur "timed out waiting for packet header". Beim Sonoff hatte ich es am Ende rangelötet, will ich eigentlich vermeiden.

**Comment by Schnup89** [comment]
Über WSL habe ich es auch gemacht, als COM Port dann /dev/ttySX    X = Com port nummer
PIN4 und PIN5 von rechts oben, passt oder?

**Comment by greynoO** [comment]
Jo, das hatte ich alles soweit richtig, die physische Verbindung ist mit den Kabeln die ich habe einfach schwierig. Jetzt habe ich es aber endlich geschafft.

[Sieht das korrekt aus?](https://abload.de/img/tasmwzkui.png)

i2cscan gibt mir
`RESULT = {"I2CScan":"Device(s) found at 0x0b 0x6f"}`

**Comment by Schnup89** [comment]
super, die gleichen devices wie bei mir, kannst du mir ein bild von der ersten oberfläche schicken? 
zum zweiten in der konsole schauen, wenn der pir funktioniert sollte da ein Text "movement" erscheinen

**Comment by greynoO** [comment]
Bild ist doch oben verlinkt, oder welche Oberfläche meinst du?

movement sehe ich bei mir leider nicht.

**Comment by Schnup89** [comment]
danke! Hab ich überlesen :)
Springt die Spannung oder bleibt die konstant?

**Comment by greynoO** [comment]
Ich musste übrigens auf "Gerät konfigurieren" und dort auswählen, nicht unter "Vorlage konfigurieren", dort gab es nur Dev-Kit.

LC709203F Spannung springt

**Comment by p-rintz** [comment]
> danke! Hab ich überlesen :)
> Springt die Spannung oder bleibt die konstant?
> 
> edit: was macht der piezo für geräusche? komische?

Modem-artige :smile: 

Bei mir ist die ganze Oberfläche *sehr* langsam. Ping von 2 sekunden ca. Und Webseite lädt nach ca einer Minute. Normal?

**Comment by Schnup89** [comment]
Okay, dann muss ich mir das mit den Werten des Spannungswandler nochmal anschauen. 
Noch einige Baustellen ;)

PIR-Sensor wird nicht mit 3,3v versorgt, da gibt es irgendwo wahrscheinlich noch ein gpio der diesen an oder ausschaltet.
Piezo bin ich gerade dran, da blick ich noch nicht ganz durch warum der immer die komischen geräusche macht.
Der Gas Sensor liefert immer den gleichen analogen Wert (4095).
Mikrofon liefert auch keine analogen Werte.

Viele Baustellen aber ich bin dran ;)

@p-rintz  Danke fürs testen!
Das Webinterface ist etwas träger ja, aber bei ich habe keine Ping-Latenzen und die Webseite ist immer innerhalb 1-2 Sekunden geladen.
Ping wird ausgeführt für 192.168.10.239 mit 32 Bytes Daten:
Antwort von 192.168.10.239: Bytes=32 Zeit=59ms TTL=255
Antwort von 192.168.10.239: Bytes=32 Zeit=61ms TTL=255
Antwort von 192.168.10.239: Bytes=32 Zeit=73ms TTL=255
Antwort von 192.168.10.239: Bytes=32 Zeit=80ms TTL=255

**Comment by Schnup89** [comment]
Update YES! Piezo funktioniert! ... das war zu einfach :D
Unter Vorlagen GPIO16 auf PWM umstellen, dann funktioniert er auch und macht keine Geräusche mehr.

**Comment by greynoO** [comment]
ah, jetzt kann ich ihn piepsen lassen... :D

**Comment by Schnup89** [comment]
Hab mir schon zwei neue bestellt... das muss laufen :)

**Comment by greynoO** [comment]
Aber wohl mit Codes, oder? Habe selbst 3 Stück hier, wäre cool, die am Ende nutzen zu können mit den Sensoren.

**Comment by Schnup89** [comment]
Was meinst du mit Codes?

Update: Hab den GPIO zum aktivieren des PIR Sensor gefunden. GPIO27 als nächstes Relay (7?) konfigurieren. Das zurücksetzen des Alarm funktioniert noch nicht, da muss ich mal in die Library schauen

**Comment by greynoO** [comment]
Ich meinte Codes von Vattenfall für Tink. Nicht für 180 EUR gekauft..

**Comment by Schnup89** [comment]
Ne Quatsch, Kleinanzeigen sehr günstig geschossen

**Comment by Schnup89** [comment]
Was können der Chip mit dem golden viereck neben dem Piezo sein?
Temperatur + Luftfeuchtigkeit? Findet ihr den Chip irgendwo im Internet?

Label: 7a1r

**Comment by greynoO** [comment]
Ja sieht so aus, Temperatur und Feuchtigkeit. Habe bei aliexpress einen 9a1r gefunden.

**Comment by Schnup89** [comment]
Perfekt, danke! Der meldet sich nicht auf dem I2C bus da auch der sensor erst mit einem gpio aktiviert werden muss (zwischen vdd und gnd liegen 0V an). Und los geht die suche ;)

**Comment by Schnup89** [comment]
> Update: Hab den GPIO zum aktivieren des PIR Sensor gefunden. GPIO27 als nächstes Relay (7?) konfigurieren. Das zurücksetzen des Alarm funktioniert noch nicht, da muss ich mal in die Library schauen

-> Funktioniert nach einem Reboot, es wird :)

**Comment by Schnup89** [comment]
Update: 
Es gibt einen zweiten I2C "Kreis" an dem aktuell laut i2scan**2**  drei Geräte hängen.
Eines davon ist auf jeden Fall der Luftqualitätssensor mit der Aufschrift 7A1R.
Aktuell spricht Tasmota nur die Sensoren der ersten I2C Gruppe an. Die von der zweiten Gruppe werden nicht angezeigt (erst wenn man die I2C Gruppe 2 auf 1 stellt)

**Comment by greynoO** [comment]
Updates du die Firmware nochmal oder ist das aktuell unsinnig?

**Comment by Schnup89** [comment]
Servus, bringt aktuell leider noch nichts da der Code für 98% der Tasmota i2c Sensoren nicht für den zweiten Bus implementiert ist. Ich such mir gerade den Weg mit dem geringsten Widerstand um die Sensoren anzusprechen... Evtl gibt's morgen ein update

**Comment by BamBam191** [comment]
Danke für die Arbeit

**Comment by blautob** [comment]
Von mir auch! bleib dran. Das wird ziemlich geil wenn alles über tasmota funktioniert.

**Comment by Schnup89** [comment]
Ich drehe die i2c Bus Gruppe.
To-Do:
-spannungssensor hier gibt es einen i2c Bug im esp Core Code, müssen wir warten... Den Stelle ich nach hinten
-rtc Chip Lib muss ich umschreiben für Support in der zweiten i2c Gruppe 
- prüfen der beiden unbekannten i2c Geräte

Ein Update gibt's heute nicht ich war lange an dem Spannungssensor

Gruß

**Comment by Schnup89** [comment]
PS: der luftsensor hdc1080 funktioniert 💯

**Comment by Schnup89** [comment]
Ich hau gleich eine neue Version in das Repository.
Der LiPo-Sensor ist deaktiviert, zeigt aktuell sowieso nur falsche Werte an.

Ihr könnt mit dieser Version mal das Mikrofon testen, mehr dazu im Issue.

**Comment by blautob** [comment]
Hab mich jetzt auch ans flashen gemacht und hat einwandfrei nach deiner Anleitung geklappt.
Ich spiele aktuell mit der Oberfläche rum...

**Comment by blautob** [comment]
Das sind übrigens meine Werte:
ADS1115 Analog 2 und 3 verändern sich Analog 0 und 1 nicht

![grafik](https://user-images.githubusercontent.com/24385671/125634309-81d7c82e-ca39-497e-be86-a8e7466255ac.png)

**Comment by MichlW** [comment]
Sind 28,4 °C realistisch oder ist da noch ein Käfer drin?
Kann es sein, dass es im Smart Ring durch den ESP wärmer wird und hier eine Offset abhängig der ESP-Temperatur sinnvoll wäre?

Habe mich schon die ganze Zeit gefragt ob die gemessenen Werte _im_ Smart Ring über die Realität außerhalb aussagen können?!?

**Comment by blautob** [comment]
Ist (noch) ungenau hab aktuell mal nachgemessen delta ca. 4 Grad und Luftfeuchtigkeit 4% ggu meiner Refernz

**Comment by greynoO** [comment]
Bei mir aktuell 30.7°C laut HDC1080, real eher um 26°C

**Comment by Schnup89** [comment]
Der ESP hat Teilweise 50°C da wirds im Ring wahrscheinlich etwas wärmer werden. 
Entweder in dem Homeautomatisierung System oder alternativ mit dem tasmota Befehl tempoffset die Temperatur anpassen.

**Comment by blautob** [comment]
@Schnup89 spricht was dagegen nach dem flashen mit der aktuellsten firmware die batterien wieder einzubauen? Will funkenregen vermeiden (siehe dein 1. post) ;-)

**Comment by Schnup89** [comment]
Ne kein Problem du kannst diese einsetzen. Der Funkenregen wurde durch die Spitze meines Messgerätes ausgelöst, nicht durch die Batterien :)

**Comment by Schnup89** [comment]
> > danke! Hab ich überlesen :)
> > Springt die Spannung oder bleibt die konstant?
> > edit: was macht der piezo für geräusche? komische?
> 
> Modem-artige 😄
> 
> Bei mir ist die ganze Oberfläche _sehr_ langsam. Ping von 2 sekunden ca. Und Webseite lädt nach ca einer Minute. Normal?

Fehler gefunden! Relay 5 nimmt den Strom von einigen IC's die bringen dann den I2C Bus durcheinander weshalb der ESP dann etwas träge wird. Am besten Relay 5 (gpio33) mit der neuen Binary immer auf 1 lassen

**Comment by Schnup89** [comment]
Neue Version ist hochgeladen, Vorsicht ich habe manche Relays Invertiert sodass Sie auch zur Funktion passen.
Mit den vielen Sensoren ist der ESP etwas träge funktioniert aber ;)

Probiert aus und lasst gebt mir Rückmeldungen!

**Comment by blautob** [comment]
![Bildschirmfoto 2021-07-16 um 08 39 57](https://user-images.githubusercontent.com/24385671/125903679-07ecdfd2-8091-4bd4-a44a-62ac0c89f5fd.png)

Reaktionszeit bei mir selbst mit sleep 1 noch sehr gut.
Die Werte zu Temperatur und Luftfeuchtigkeit passen mit dem neuen Update bei mir gar nicht mehr. Delta 15Grad. Habe aber den Ring jetzt auch wieder "eingepackt". Schraube ich nacher nochmal auf und prüfe.
Movement Sensor funktioniert (Relays 4 an/aus)-Fehler konnte ich reproduzieren.
Mikrophone spuckt bei mir bislang keine Werte aus. Hatte paar Minuten den Alarm und laute Musik an, aber bewegt sich aber nix in der ÜBersicht.
> Am besten Relay 5 (gpio33) mit der neuen Binary immer auf 1 lassen
Das Relay 5 hab ich auf 0 gelassen, setze ich es auf 1 bleiben die ADS1115 Werte auf 0.

Was ich noch schick fände (weiß nicht ob man das selbst anpassen kann) wenn in der ÜBersicht hinter den Sensoren noch die Relays Nummer angezeigt wird z.b. Movement (4).

Ansonsten bin ich jeden Tag begeistert und gespannt auf deine Updates! Weiter so und vielen Dank!

**Comment by Schnup89** [comment]
Kannst du deine Konfiguration unter Konfiguration Reset einmal zurücksetzen? Wenn Relay 5 aus ist, dürfte der ADS und HDC Sensor nichts mehr anzeigen.

**Comment by blautob** [comment]
Hab die Konfig zurückgesetzt. Ja, wenn RElay 5 aus ist gibt es keine ADS und HDC Werte

**Comment by blautob** [comment]
Microphone Noise funktioniert (bewegt) sich jetzt auch nach dem Konfig Reset

**Comment by Schnup89** [comment]
Ah Perfekt, wollte gerade ragen :) Temperatur auch im Normalbereich? Bei mir zeigt er valide Temperaturwerte an.

**Comment by blautob** [comment]
https://user-images.githubusercontent.com/24385671/125920334-4dafc7e8-a315-4f57-a207-db8bed8ce18b.mov

Temperatur passt irgendwie noch nicht (auch trotz Reset) und entfernen des Rings.

**Comment by Schnup89** [comment]
Neue Version ist da:
fixed: Mikrofon - Abfrage für "mikrofon deaktiviert" angepasst -> anstatt 81.9db wird jetzt 0db angezeigt
fixed: Bewegungsmelder 2 Sekunden Bug
fixed: Bewegungsmelder An/Aus Problem -> Alles 30 Sekunden Config schreiben
added: Kommando: "Sensor91 SetV, x"  x = 0..4095 setzt PWM Output für GAS Heater

**Comment by Schnup89** [comment]
Neue Version ist da:
fixed: Spannungsanzeige - Spannung
fixed: Spannungsanzeige - Cell Remaining
fixed: Spannungsanzeige - Temperatur
added: Spannungsanzeige - RSOC Charge
added: Switch2 ist der Alarm Eingangsping für gpio23
added: "Sensor89 alarmperc, x" Kommando zum setzen der Prozentschwelle für das Auslösen des Alarm

**Comment by greynoO** [comment]
Ich habe den Ring jetzt mal über MQTT in HomeAssistant integriert. Da aber nur alle paaren Minuten der aktuelle Status gemeldet wird, ist zum Beispiel der PIR-Sensor nicht wirklich zu gebrauchen. Gibt es hier eine Möglichkeit, das irgendwie einzustellen? Ggf. Dass bei Movement direkt die gemeldet wird? Ich habe nicht wirklich Ahnung von Tasmota, daher die Frage.

**Comment by Schnup89** [comment]
Ich muss heute Abend Mal schauen ob meine eigenen "Sensoren" den Status per json melden, da hatte ich bisher noch kein Augenmerk drauf. Stimmt, der kleinste mögliche wert ist 19 Sekunden für den json Status aktualisierung. Ich lasse es bei Bewegung aktualisieren mit der nächsten version

**Comment by Schnup89** [comment]
Update kommt gleich:
added:  Spannungssensor - JSON Daten/MQTT wird nun richtig ausgegeben
added:  PIR - Sensordaten werden bei Bewegung aktualisiert
added:  LED - Color Picker, Steuerung per Tasmota Light befehle!
added:  WebButtons -  Anleitung / Beschriftung
changed: Relays! Bitte Konfiguration zurücksetzen und Template neu auswählen!
bug: Piezo nicht nutzbar wegen LED Picker... Tasmota ding, muss ich checken

**Comment by greynoO** [comment]
Cool, danke dir. Langfristig muss man wohl doch auch nochmal den Energiesparmodus angucken, die Akkus bei meinem sind um ca. 25% runter nach 24 Std.

**Comment by blautob** [comment]
Absoluter Hammer was du hier in 1-2 Wochen abgeliefert hast. Energiesparfunktionen wären echt noch mega.
Wenn man das individuell setzen könnte, Mir würde Temperaturmessung bspw, alle 5min reichen oder LiPo Spannung paar mal am Tag wenn dadurch die Batterielaufzeit deutlich gesteigert werden kann.

**Comment by Trashwarez** [comment]
Definitiv klasse, was da so entstanden ist. Großes Kompliment. Das Thema Energiesparen halte ich auch für sehr wichtig. Denn wo die Energie hingeht, das sieht man an den Screenshots hier. Auch meine Messergebnisse sind ähnlich, also 50 Grad der ESP und 45 Grad die "Außentemperatur".

**Comment by blautob** [comment]
https://twitter.com/homelivy/status/1422578168188313608?s=21
😉

**Comment by Schnup89** [comment]
> Definitiv klasse, was da so entstanden ist. Großes Kompliment. Das Thema Energiesparen halte ich auch für sehr wichtig. Denn wo die Energie hingeht, das sieht man an den Screenshots hier. Auch meine Messergebnisse sind ähnlich, also 48 Grad der ESP, 47 Grad die "Außentemperatur" und das Gehäuse ist beim Prozessor auch spürbar warm. Hat jemand dieses leise Knacksen wegbekommen?

Das dürfte mit der Anpassung des Buzzers erledigt sein.

**Comment by Schnup89** [comment]
> https://twitter.com/homelivy/status/1422578168188313608?s=21
> 😉

Das prüfe ich mal nächste Woche… Der Sensor fehlt wohl auf meiner Platine, oder es ist eine Kopie im Einsatz 💡

**Comment by micdis** [comment]
Vielen Dank erstmal für die ganzen Mühen! :-) sehr beeindruckend!

ich habe mich heute mal ans flachen gewagt und ich konnte den ESP nur in den flash-müde bringen, indem ich ihn von extern mit 3,3V versorgt habe. komisch.

NAch dem flashen fehlt mir nun auch die Sensoren für Spannung und Gas. Und wenn ich den PIR an mache, dann springt meine Temperatur auf -40°C sowie die Feuchtigkeit auf 100%. Leider bekomme ich auch keine Werte für Movement oder Noise. 

Hab ich was kaputt gemacht auf der Platine, oder gibt es eine erklärbare Lösung?

Danke schnonmal im Voraus!

**Comment by Schnup89** [comment]
Hi, hast du das Template ausgewählt? 
"Einstellungen" -> "Gerät" -> "Gerätetyp" hier Livy-Ring auswählen.

**Comment by micdis** [comment]
ja, hab ich - die LED Steuerung geht ja und der Temperatur-/Feuchte-Sensor liefert (mittlerweile korrekte) Daten,....

**Comment by Schnup89** [comment]
OK, der AirQ Button muss immer auf "on" stehen sonst funktionieren einige IC's nicht. Wenn die Sensoren nicht mehr erkannt werden hilft (aktuell) nur ein reboot.

**Comment by micdis** [comment]
wenn. PIR auf ON steht, "sieht" er den Temp Sensor nicht. Werte für MIC und PIR hatte ich auch noch nie.
eine Idee, wie ich raus bekomme, ob er die Sensoren erkennt, oder wo der Fehler liegt!?

**Comment by Schnup89** [comment]
Alle relays auf "on" stellen und neu starten dann muss er eigentlich alle Sensoren erkennen.
Kannst du Mal ein Bild deiner Platine reinstellen? Evtl. gibt's auch ne neue version

**Comment by micdis** [comment]
dann erkennt er gar nichts mehr:

![1655C65C-3B48-4118-9C20-86ED17C2CF15](https://user-images.githubusercontent.com/37632449/131244180-5c76576a-8a27-40b6-a4f8-365d3da32bf8.png)

hier die Platine:

![Uploading 823E2218-EAD6-4B63-849B-453492327B97.jpeg…]()

ist auch eine G2

**Comment by micdis** [comment]
![EAF3FAF4-3179-422F-BF16-C3D89B79DC70](https://user-images.githubusercontent.com/37632449/131244210-6194f47d-b02d-4af7-9564-50b44c51a0f3.jpeg)

**Comment by Schnup89** [comment]
Oh oh... Das ist eine Version/revision.
Kannst du mir ein Bild des Aufklebers mit dem modell senden?

**Comment by micdis** [comment]
gern! 😎 

![AEC2967C-7CAD-414F-8185-18525BC21C8C](https://user-images.githubusercontent.com/37632449/131244996-2af5ea56-e03a-4b13-87f5-917cbbddb160.jpeg)

**Comment by Schnup89** [comment]
Neue Version hochgeladen, die Konfiguration des Bewegungsmelders kann nun angepasst werden.

**Comment by Schnup89** [comment]
Ich mache hier mal zu, alles weitere bitte per Issue diskutieren/anregen.
