### ISSUE TITLE
which 4 files to upload?

### ISSUE THREAD

**Issue by rthiel** [Schnup89/LIVY_RING_G2-Tasmota#10]
Hi got a ring and wanted to flash tasmota. Tried following your link (https://github.com/arendst/Tasmota/tree/firmware/firmware/tasmota32/ESP32_needed_files) but it didn't work. Can you please help me finding the right 4 files?
thanks

**Comment by rthiel** [comment]
guess I found them: https://github.com/arendst/Tasmota-firmware/tree/main/release-firmware/tasmota32/ESP32_needed_files
but get the following error when flashing the files: "Detected overlap at address: 0x8000 for file: partitions.bin"

**Comment by Schnup89** [comment]
Thanks for the flash-files url information, I've updated the URL in the Readme.

- Which flasher do you use?
- The flash Files been updated 22 days ago, I havent tried them. At the end of the next Week i can Check If they have been changed

**Comment by Schnup89** [comment]
Please check Jason‘s note about how to download the files, mayen this helps?

https://github.com/arendst/Tasmota/issues/8906#issuecomment-663050045

**Comment by rthiel** [comment]
thanks that helped - cloned that repo as well and finally got the right binaries

**Comment by lazariv** [comment]
Unfortunately the link is not working again:
https://github.com/arendst/Tasmota-firmware/tree/main/release-firmware/tasmota32/ESP32_needed_files

Can you please update?

**Comment by Schnup89** [comment]
https://github.com/arendst/Tasmota-firmware/tree/main/static/esp32

Updated in the readme, thanks for the information

**Comment by jojeji** [comment]
link seems to be outdated. Can anyone please update the link. I can´t find the 4 files.

**Comment by Schnup89** [comment]
It seems like the flashing procedure has changed for the actual tasmota binarys.

I Look into it this weekend

**Comment by Schnup89** [comment]
https://tasmota.github.io/docs/ESP32/#flashing

You could try flashing the ESP with this instructions and the mentioned tasmota Firmware, after that flash the tasmota binary from here. It **should** not Break anything but I have Not tested it

**Comment by jojeji** [comment]
Yep it worked. I used the "ESP-Flasher.exe" and the binary from this repo. Thanks :)
