### ISSUE TITLE
Empfindlichkeit Bewegungssensor

### ISSUE THREAD

**Issue by rthiel** [Schnup89/LIVY_RING_G2-Tasmota#12]
Hallo zusammen,
ich hab eine tasmota rule auf den Bewegungssensor erstellt 
`rule1 on pyq#Movement=true do backlog...`
Leider triggert der Bewegungssensor manchmal ohne dass jemand im Raum ist - in der Original Livy App konnte man da irgendwie eine Empfindlichkeit einstellen. Klar kann ich den auf Serverseite entprellen und erst ab 3 Meldungen innerhalb von 10s etwas auslösen. Wenn es aber die Möglichkeit gäbe, den Sensor etwas unempfindlicher zu machen, dann wäre mir das am liebsten. Für Ideen bin ich dankbar.

**Comment by Schnup89** [comment]
Schaue ich mir nächste Woche an.
Das Problem dabei ist das Speichern von pesisententen Werten im Flash, da ist einiges zu tun beim Tasmota-Unterbau deswegen bin ich da eher vorsichtig mit.

Falls du den Code von der Source selbst kompiliert, kannst du dir hier die Sensitivität einstellen:

https://github.com/Jason2866/LIVY_RING_G2-Tasmota/blob/work/tasmota/xsns_90_pyq1548.ino
Zeile 32-36

**Comment by rthiel** [comment]
Danke für den Hinweis, das versuch ich mal - welches build-target wäre denn das richtige "tasmota32" - hab keines für den "ring" konkret entdeckt. Wenn ich das tu' bekomme ich ein binary, welches leicht anders aussieht (knapp 1k kleiner als das vorcompilierte). Kann ich das "bedenkenlos" OTA flashen und bei Problemen wieder das alte OTA drüber flashen?
Bzgl. status - ja in Status 10/8 ist die Info auch enthalten.

**Comment by Schnup89** [comment]
Habe tasmota32-DE als target genutzt.
Solange du ein Binary mit dem Tasmota32 traget flashest dürfte es keine Probleme zwischen den Versionen per OTA Flash geben.

**Comment by rthiel** [comment]
top danke - hat funktioniert.
