### ISSUE TITLE
{"Command":"Error"} beim Ausführen von Kommandos

### ISSUE THREAD

**Issue by micdis** [Schnup89/LIVY_RING_G2-Tasmota#14]
die angegebene Config führt bei mir zu einem Fehler:

`20:00:47.574 CMD: Sensor90 sens, 30`
`20:00:47.592 MQT: stat/livy_26B680/RESULT = {"Command":"Error"}`

**Comment by Schnup89** [comment]
Hi, das ist nur Kosmetik das Kommando sollte trotzdem ausgeführt worden sein.

**Comment by micdis** [comment]
ah, okay. Danke dir! :- )

**Comment by Schnup89** [comment]
Ich schaue mir das die Tage an

**Comment by Schnup89** [comment]
erledigt
https://github.com/Jason2866/LIVY_RING_G2-Tasmota/commit/cb881e0bcbba04804eb3f0faf904f9874ff9236b
