### ISSUE TITLE
Flashen funktioniert nicht

### ISSUE THREAD

**Issue by reschandreas** [Schnup89/LIVY_RING_G2-Tasmota#15]
Hi!

Ich habe ein kleineres Problem beim Flashen der Firmware, es funktioniert einfach nicht. Die Seriennummer und das PCB Layout entsprechen jeweils der unterstützen Version. Ich befolge genau die Anleitungen hier im Repo und halte die Jumper-Kabel direkt an die Pins des ESP32.

Egal was ich mache, das `esptool` kann nicht mit der Seriellen Schnittstelle kommunizieren und bricht ab. Zwei verschiedene TTL-Adapter und vier verschiedene Hosts (VM, RPI und normales Linux) haben auch nichts gebracht. Hat jemand irgendwelche Tipps für mich wie ich das Teil trotzdem flashen kann?
Danke!

**Comment by Schnup89** [comment]
Hey, ich finde gerade den Beitrag nicht, aber ich meine es hätte jemand berichtet dass es bei ihm nur im Batteriebetrieb oder im Ladebetrieb (mit angestecktem USB Kabel) funktionierte.

Kannst du das mal testen?

**Comment by reschandreas** [comment]
Hi, hab beides schon probiert, hat leider nichts geklappt.

**Comment by Schnup89** [comment]
Bist im Flash Modus? Das siehst du wenn die LED dauerhaft grün leuchtet.

**Comment by reschandreas** [comment]
Hat jetzt doch endlich funktioniert mit dem Laptop eines Freundes (mit Linux und dem esptool).
Danke für die Hilfe!
