### ISSUE TITLE
Tasmota 10 

### ISSUE THREAD

**Issue by blautob** [Schnup89/LIVY_RING_G2-Tasmota#16]
Hi

habe gerade gesehen dass die Tasmota 10 einige Verbesserungen im Hinblick auf ESP32 bringt.
Macht es Sinn hier nochmal ein Update zu machen?

Btw, der Livy läuft bei mir stabil seit geraumer Zeit im Home Assistant :-)
Schade dass die Gas Funktion bisher noch nicht so läuft wie erhofft.

**Comment by Schnup89** [comment]
Habe mal das vorkompilierte Binary (tasmota32-bluetooth.bin) draufgehauen, hat funktioniert. Nur eben ohne die Custom-Sensoren und dem Buzzer-Bug.

Habe daraufhin eine fork von Tasmota10 gezogen und quick&dirty mit C&P die Custom-Sensoren versucht zu aktivieren:
https://github.com/Jason2866/LIVY_RING_G2-Tasmota/tree/Tasmo10

Baustellen:
- LivyRing-Template anpassen
- PYQ GPIO Pins nicht sichtbar in Template -> PYQ funktioniert nicht
- MIC zeigt 0db an... da tappe ich noch im dunkeln

Rest sollte funktionieren... schaue die Tage nochmal drüber und gebe euch dann eine Test Binary

**Comment by dmahhhh** [comment]
Moin,
ich habe die tasmota32.bin (Tasmota10) auf mein Livy geflasht. Wäre dir für ein angepasstes Binary auf Basis der 10'er dankbar. Aktuell bekomme ich "Signature Failed" beim Versuch die Firmware upzugraden.

VG

**Comment by Schnup89** [comment]
> Moin, ich habe die tasmota32.bin (Tasmota10) auf mein Livy geflasht. Wäre dir für ein angepasstes Binary auf Basis der 10'er dankbar. Aktuell bekomme ich "Signature Failed" beim Versuch die Firmware upzugraden.
> 
> VG

Habe eine Version auf basis der aktuellen Tasmota 12 erstellt. Siehe #20
