### ISSUE TITLE
Werte fehlen im Vergleich zum Readme Screenshot

### ISSUE THREAD

**Issue by muhkuhgh** [Schnup89/LIVY_RING_G2-Tasmota#17]
Moins,

Vielen Dank für die Mühe hier! Hab es gerade mal auf einen meiner Smart Ringe aufgespielt, lief soweit problemlos.

192BG.. Seriennummer.. 

Was habe ich denn falsch gemacht/übersehen/vergessen das es bei mir so ausschaut:
![grafik](https://user-images.githubusercontent.com/38386384/146784080-cdd6b9e2-5442-45f5-9c77-bdb34be64de6.png)

und viele Werte, z. B. Luftfeuchtigkeit etc. wie im Readme Screenshot fehlen?

**Comment by blautob** [comment]
klicke auf die buttons pir, airq etc. und dann neustart

**Comment by muhkuhgh** [comment]
Ahhhh... *facepalm* Danke für die schnelle Aushilfe!
Mal sehen ob ich zwischen den Feiertagen Zeit (und Lust) finde, mal bzgl. Energiesparfunktionen zu schauen..

**Comment by Schnup89** [comment]
Alles klar, top.... Uuuuuuuund zu
