### ISSUE TITLE
Buzzer in Home Assistant ?

### ISSUE THREAD

**Issue by Lordxv** [Schnup89/LIVY_RING_G2-Tasmota#18]
Hallo, 
Ich wollte einmal fragen, ob hier jmd den Buzzer aus Home Assistant heraus steuern kann. 
Mit dem Command /cm?cmnd=Buzzer%201 lässt sich der Buzzer ohne Probleme ansteuern. 
Kann man den Buzzer auch als Ausgang konfigurieren? Sozusagen als An/Aus Switch?
Oder müsste man das in Home Assistant erstellen?

Viele Grüße
Und vielen Dank für das Projekt !

**Comment by Schnup89** [comment]
Hey,

wie du den Buzzer in HA einbindest kann ich dir leider nicht beantworten.

Ich kann dir aber sagen wie er an und aus geht:

Über mqtt:
Topic: cmnd/tasmota_xxxxxx/Buzzer
Payload 1 an 0 aus

Über http:
cm?cmnd=Buzzer%201 - an
cm?cmnd=Buzzer%200 - aus

**Comment by Lordxv** [comment]
Danke für die schnelle Antwort und Hilfe.

Hier ist einmal mein Ergebnis für die Nachwelt. 
Einfach in die configuration.yaml
`switch:
  - platform: mqtt
    unique_id: buzz_switch1
    name: "Buzz Switch 1"
    command_topic: cmnd/tasmota_XXXXX/Buzzer
    payload_on: "-1,10,8"
    payload_off: "0"`
