### ISSUE TITLE
Luftqualität: CO2 und VOC-Werte (flüchtige organische Verbindungen) ?

### ISSUE THREAD

**Issue by eGit** [Schnup89/LIVY_RING_G2-Tasmota#22]
The G2 is advertised as measuring "Air Quality"

It gives an air quality score between 1/10 and 10/10 (best).

Whatever is going on with this sensor under the hood, it seems to measure both CO2 and VOCs: https://www.technikbrennpunkt.de/livy-protect-smart-ring-test-14444/#messgenauigkeit-messabweichungen

In the measurements, when the CO2 value goes up the air quality goes from 10/10 to 7/10 in the app. Also when VOC concentration is sharply increased, the Livy app alarms the user. It seems to be measuring CO2 and VOC. Only in G3 this was finalized and officially promoted but I think the rudimentary function is already there in G2.

Is it possible to read this out somehow?

**Comment by Schnup89** [comment]
With Tamota we have to read the data from the electronic chips, which -unfortunately- wont give us the numbers 1/10 to 10/10.
We have to calculate this number in the code - and we dont know the formula to get the calculations done.

In this issue we've talked about this problem:
https://github.com/Schnup89/LIVY_RING_G2-Tasmota/issues/2

There were some documents which can help to create the code, but for me this is to complicated.
[Datenblatt](https://www.sciosense.com/wp-content/uploads/documents/SC-001255-DS-2-CCS801B-Datasheet-Revision-2.pdf)
[Anwendungsdokumentation](https://www.sciosense.com/wp-content/uploads/documents/CCS801-Application-Note-Design-Guidelines.pdf)

**Comment by Schnup89** [comment]
See https://github.com/Schnup89/LIVY_RING_G2-Tasmota/issues/2
