### ISSUE TITLE
Bewegungssensor

### ISSUE THREAD

**Issue by Schnup89** [Schnup89/LIVY_RING_G2-Tasmota#4]
Nach deaktivieren/aktivieren über Relay 4 funktioniert die Bewgungserkennung nicht mehr.

Könnt ihr das reproduzieren?

**Comment by blautob** [comment]
Ja. Geht erst nach einem Neustart wieder

**Comment by blautob** [comment]
Bug bleibt bestehen auch nach Config-Reset

**Comment by Schnup89** [comment]
OK, ich schaue mir das als nächstes an.
Zusätzlicher Bug: Bei Movement-Erkennung friert ESP für 2 Sekunden ein, hier muss ich das Sleep Kommando entfernen

**Comment by Schnup89** [comment]
fixed: Bewegungsmelder 2 Sekunden Bug
fixed: Bewegungsmelder An/Aus Problem -> Alle 30 Sekunden Config schreiben

Der Bewegungsmelder muss initial beim starten mit einer Konfiguration gefüllt werden.
Da ich keine elegante Lösung habe wie ich das Relay abfragen kann ohne 10 Umwege schreibe ich einfach alle 30 Sekunden die Konfiguration auf den Sensor, damit sollte nach dem Aus und Einschalten des Sensors nach Max. 30 Sekunden die Erkennung wieder funktionieren.
