### ISSUE TITLE
LC709203F Spannungssensor

### ISSUE THREAD

**Issue by Schnup89** [Schnup89/LIVY_RING_G2-Tasmota#5]
Er funktioniert, es lag wohl an der crc8 Berechnung, mit eigenen "read" funktionen funktioniert nun auch der Datenabruf von Spannungssensor IC.

Ich konnte noch keinen Unterschied zwischen Cell Remaining und RSOC Charge feststellen, evtl. fällt euch da etwas auf.
Die Temperatur ist auf Thermistor-Source eingestellt, evtl. lassen wir das auch Weg da wir schon einige Temperatursensoren im Ring haben.
Mit dem Befehl "Sensor89 alarmperc, 30" können wir festlegen dass ab 30 Prozent Kapazität ein Alarm auf dem gpio23 (gemaped auf switch2) angezeigt werden soll. Das funktioniert noch nicht.
Test mit Konsolen Kommando: "Status 10" -> Dort wird ziemlich am Anfang der Status des Switch2 angezeigt (OFF Kein Alarm | ON Alarm)

fixed: Spannungsanzeige - Spannung
fixed: Spannungsanzeige - Cell Remaining
fixed: Spannungsanzeige - Temperatur
added: Spannungsanzeige - RSOC Charge
added: Switch2 ist der Alarm Eingangsping für gpio23
added: "Sensor89 alarmperc, x" Kommando zum setzen der Prozentschwelle für das Auslösen des Alarm

Todo:
- Alarmpin funktioniert nicht
- Temperatur anzeige entfernen
- Prüfen ob das setzten des Alarms nach einem Neustart wiederhholt werden muss

**Comment by greynoO** [comment]
Hier noch eine Frage, bei mir zeigte er gestern bei Cell Remain 2% an, heute Vormittag waren die Akkus anscheinend leer. Jetzf habe ich den Ring bestimmt 10 Std. am Ladegerät gehabt und nun zeigt es 5%. Sollte es da irgendwann mal 100% stehen? Vielleicht sind auch meine Akkus kaputt, ich hatte einen für einige Zeit versehentlich falsch herum drin und der wurde dadurch ziemlich warm.

**Comment by Schnup89** [comment]
Ups, das war bestimmt nicht gut für den Akku.
Lass Mal den betroffenen Akku raus (funktioniert auch mit 1 oder 2) und schau mal ob die anderen wieder aufgeladen werden

**Comment by greynoO** [comment]
Ok, habe mal andere rein gemacht, da sind es über 50%. Scheint wohl wirklich was kaputt gegangen zu sein. Schade 😒

**Comment by Schnup89** [comment]
Hast du einen Multimeter? Wenn ja, müsste die Defekte Batterie weniger Spannung anzeigen

**Comment by greynoO** [comment]
Probiere ich mal aus, danke!

**Comment by greynoO** [comment]
Zeigen alle ~3.6V

**Comment by Schnup89** [comment]
Sorry, dann hab ich leider keine Tipps mehr...

**Comment by Schnup89** [comment]
Alarm wurde fest auf 20 Prozent gesetzt.
Temperatur lasse ich drin, die tut keinem Weh...

**Frage an alle:**
Ich kann den Sensor in den Sleep Modus schicken, habe aber noch keine "Best Practice" dazu gefunden.
Folgende Optionen schweben mir vor:
- Nach 30 Minuten aufwecken, 2 Minuten aktiv lassen, auslesen, dann wieder schlafen schicken.
- Nach 30 Minuten aufwecken, auslesen, schlafen schicken.

**Comment by greynoO** [comment]
Wo ist der Vorteil zu zwei Minuten aktiv?

**Comment by Schnup89** [comment]
Ich bin mir unschlüssig ob und wie die rsoc (relative state of charge) kalkulation darunter leidet. Finde leider keine Beispiele dazu im Netz. Ich könnte Option 2 ohne aktiv lassen implementieren, dann müsste man aber schauen ob die Kalkulation für die Rest-Prozenz-Angabe noch passt

**Comment by Schnup89** [comment]
Alarmpin kann nun auch manuell gesetzt werden, ich denke der Spannungssensor läuft jetzt wie er soll.
Wenn es Probleme damit gibt bitte ein Issue erstellen.
In der Readme ist die Konfiguration erklärt.
